### ISSUE TITLE
`peek` raises `TypeError`

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2cli#101]
e.g.:
```bash
(q2dev) ☁  moving-pictures  qiime tools peek cm1441/evenness-correlation.qzv
UUID:        e65966a0-a4a7-4490-9900-c8bd491edd85
Type:        Visualization
Data format: Traceback (most recent call last):
  File "/Users/matthew/miniconda3/envs/q2dev/bin/qiime", line 11, in <module>
    load_entry_point('q2cli', 'console_scripts', 'qiime')()
  File "/Users/matthew/miniconda3/envs/q2dev/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/matthew/miniconda3/envs/q2dev/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/matthew/miniconda3/envs/q2dev/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/matthew/miniconda3/envs/q2dev/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/matthew/miniconda3/envs/q2dev/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/matthew/miniconda3/envs/q2dev/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/matthew/caporasolab/q2cli/q2cli/tools.py", line 80, in peek
    click.secho(metadata.format)
  File "/Users/matthew/miniconda3/envs/q2dev/lib/python3.5/site-packages/click/termui.py", line 420, in secho
    return echo(style(text, **styles), file=file, nl=nl, err=err, color=color)
  File "/Users/matthew/miniconda3/envs/q2dev/lib/python3.5/site-packages/click/termui.py", line 393, in style
    return ''.join(bits)
TypeError: sequence item 0: expected str instance, NoneType found
```

**Comment by ebolyen** [comment]
Visualizations have a format of `None`, we'll need to handle this explicitly in the CLI.
