### ISSUE TITLE
Installed qiime2 but getting SyntaxError: invalid syntax error

### ISSUE THREAD

**Issue by Calvin2077** [qiime2/q2cli#251]
Hello everyone,

I hope you all are safe and healthy. I am new to qiime2 but I do have some experience especially with earlier versions. As a result I was very excited when the newest update was released qiime2-2020.11. However, upon installing it I got this massive SyntaxError: invalid syntax as seen below 

SyntaxError: invalid syntax
(qiime2-2020.11_better) Calvin-Cornells-MacBook-Pro:~ eyehillentertainment$ qiime --help
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/qiime", line 11, in <module>
    load_entry_point('q2cli==2020.11.1', 'console_scripts', 'qiime')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/q2cli-2020.11.1-py2.7.egg/q2cli/__main__.py", line 11, in <module>
    import q2cli.commands
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/q2cli-2020.11.1-py2.7.egg/q2cli/commands.py", line 226
    options = [*self._inputs, *self._params, *self._outputs, *self._misc]

And as a result, of this error qiime2 doesn't work at all. Hence if I could please have some help in solving this problem it would be greatly appreciated.

Thank you very much, and happy holidays everyone.

**Comment by thermokarst** [comment]
Hi @Calvin2077! We provide user and technical support over at https://forum.qiime2.org - please come find us there! Please be prepared to share the steps you ran in order to install, as well. Thanks!

**Comment by Calvin2077** [comment]
Hello thermokarst,

Awesome thank you very much for your help it is greatly appreciated. Therefore I shall defiantly post my problem using the link you provided.

Thank you again and I hope you have a wonderful day.
