### ISSUE TITLE
Update to click==8.0.0 breaks cache refresh on 2021.8.dev

### ISSUE THREAD

**Issue by misialq** [qiime2/q2cli#259]
**Bug Description**
After installation of qiime2 + q2cli latest dev version (see details below) it is not possible to refresh cache due to a TypeError (see below).
It looks like the issue is likely due to some update in `click`: when I try pinning it to 7.1.2 everything works as expected. When it's not pinned (i.e. version 8.0.0 is being installed) the error occurs.

**Steps to reproduce the behavior**
1. Create the following conda environment:
`conda create -y -n test-env -c https://packages.qiime2.org/qiime2/2021.8/staged -c conda-forge -c bioconda -c defaults qiime2 q2cli`
2.  Activate and refresh cache:
`conda activate test-env`
`qiime dev refresh-cache`
3. Observe the following error:
```
Traceback (most recent call last):
  File "/Users/mziemski/miniconda3/envs/test-env/bin/qiime", line 11, in <module>
    sys.exit(qiime())
  File "/Users/mziemski/miniconda3/envs/test-env/lib/python3.8/site-packages/click/core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mziemski/miniconda3/envs/test-env/lib/python3.8/site-packages/click/core.py", line 1058, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/Users/mziemski/miniconda3/envs/test-env/lib/python3.8/site-packages/click/core.py", line 927, in make_context
    self.parse_args(ctx, args)
  File "/Users/mziemski/miniconda3/envs/test-env/lib/python3.8/site-packages/q2cli/click/command.py", line 43, in parse_args
    return super().parse_args(ctx, args)
  File "/Users/mziemski/miniconda3/envs/test-env/lib/python3.8/site-packages/click/core.py", line 1621, in parse_args
    rest = super().parse_args(ctx, args)
  File "/Users/mziemski/miniconda3/envs/test-env/lib/python3.8/site-packages/click/core.py", line 1372, in parse_args
    parser = self.make_parser(ctx)
  File "/Users/mziemski/miniconda3/envs/test-env/lib/python3.8/site-packages/q2cli/click/command.py", line 33, in make_parser
    param.add_to_parser(parser, ctx)
  File "/Users/mziemski/miniconda3/envs/test-env/lib/python3.8/site-packages/click/core.py", line 2643, in add_to_parser
    parser.add_option(
  File "/Users/mziemski/miniconda3/envs/test-env/lib/python3.8/site-packages/q2cli/click/parser.py", line 126, in add_option
    option = Q2Option(opts, dest, action=action, nargs=nargs,
TypeError: __init__() got multiple values for argument 'obj'
```

**Expected behavior**
It is possible to refresh cache without an error.

**Computation Environment**
- OS: macOS Catalina 10.15.7
- QIIME 2 Release: 2021.8.dev
- qiime2==`qiime2/2021.8/staged/osx-64::qiime2-2021.8.0.dev0+3.g288d15d-py38_0`
- q2cli==`qiime2/2021.8/staged/osx-64::q2cli-2021.8.0.dev0+2.g7dd03e7-py38_0`

**Comment by thermokarst** [comment]
Thanks @misialq, this is on our radar, q2cli doesn't know how to work with click 8 just yet, as you point out. Take a peek at [busywork](busywork.qiime2.org):

https://busywork.qiime2.org/teams/main/pipelines/master-distribution/jobs/unit-test-q2cli/builds/124

In the meantime, I support updating the conda deps in this project to pin click to <8. Maybe you can update the title of this issue to indicate this is about click 8? Thanks!
