### ISSUE TITLE
Provide additional information in `import` help string

### ISSUE THREAD

**Issue by wasade** [qiime2/q2cli#60]
The [help](https://github.com/qiime2/q2cli/blob/d4a2e9a0ef1bee7b9a192e5e2f0acb57e71ce42d/q2cli/tools.py#L56) string for `import` indicates that `--input-path` can be a file or directory, however it appears only directories are allowed. This contradicts the import example on the wiki as well

```
$ qiime tools import --type "SampleData[SequencesWithQuality]" --input-path demo.fastq.gz --output-path demo-artifact
Traceback (most recent call last):
  File "/Users/mcdonadt/miniconda3/envs/humann2/bin/qiime", line 9, in <module>
    load_entry_point('q2cli', 'console_scripts', 'qiime')()
  File "/Users/mcdonadt/miniconda3/envs/humann2/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mcdonadt/miniconda3/envs/humann2/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/mcdonadt/miniconda3/envs/humann2/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mcdonadt/miniconda3/envs/humann2/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mcdonadt/miniconda3/envs/humann2/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mcdonadt/miniconda3/envs/humann2/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/mcdonadt/ResearchWork/software/q2cli/q2cli/tools.py", line 66, in import_data
    view_type=source_format)
  File "/Users/mcdonadt/ResearchWork/software/qiime2/qiime/sdk/result.py", line 191, in import_data
    return cls._from_view(type_, view, view_type, provenance)
  File "/Users/mcdonadt/ResearchWork/software/qiime2/qiime/sdk/result.py", line 214, in _from_view
    result = transformation(view)
  File "/Users/mcdonadt/ResearchWork/software/qiime2/qiime/core/transform.py", line 56, in transformation
    self.validate(view)
  File "/Users/mcdonadt/ResearchWork/software/qiime2/qiime/core/transform.py", line 113, in validate
    view.validate()
  File "/Users/mcdonadt/ResearchWork/software/qiime2/qiime/plugin/model/directory_format.py", line 163, in validate
    raise ValueError("%r is not a directory." % self.path)
ValueError: InPath('demo.fastq.gz') is not a directory.
```

**Comment by ebolyen** [comment]
What's happening is that the `SampleData[SequencesWithQuality]` default format has `n` files in it. The case where you can provide a single file is when the default format has only a single known file. In that case simply providing a single file of the same format is sufficient.

**Comment by ebolyen** [comment]
None of that is particularly obvious though, so as a documentation note we will want to figure out how to explain the relationship between semantic types, directory formats, and file formats in the context of importing.

**Comment by jairideout** [comment]
This comment was in reference to the wiki, which is long gone. We've expanded the [import tutorial](https://docs.qiime2.org/2017.2/tutorials/importing/), which will hopefully make this clearer.
