### ISSUE TITLE
Munging of output name is incomplete

### ISSUE THREAD

**Issue by wasade** [qiime2/q2cli#61]
I was specifying an outputs in a plugin, and originally had `[('foo-bar', Thing)]`, however, this resulted in a traceback from q2cli as it didn't fully munge the name. The command line argument needed was `--o-foo-bar`, q2cli was looking for `o_foo-bar` and throwing a `KeyError`. Removing the `-`, and using `foobar` seemed to unstick this. Full traceback below:

``` python
$ qiime humann2 humann2 --i-samples fmt-tutorial-per-sample-fastq.qza --o-gene-families fooa --o-path-abundance foob --o-path-coverage fooc
Traceback (most recent call last):
  File "/Users/mcdonadt/miniconda3/envs/humann2/bin/qiime", line 9, in <module>
    load_entry_point('q2cli', 'console_scripts', 'qiime')()
  File "/Users/mcdonadt/miniconda3/envs/humann2/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mcdonadt/miniconda3/envs/humann2/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/mcdonadt/miniconda3/envs/humann2/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mcdonadt/miniconda3/envs/humann2/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mcdonadt/miniconda3/envs/humann2/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mcdonadt/miniconda3/envs/humann2/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/mcdonadt/ResearchWork/software/q2cli/q2cli/commands.py", line 137, in __call__
    outputs, missing_out = self.handle_out_params(kwargs)
  File "/Users/mcdonadt/ResearchWork/software/q2cli/q2cli/commands.py", line 196, in handle_out_params
    outputs.append(handler.get_value(kwargs, fallback=fallback))
  File "/Users/mcdonadt/ResearchWork/software/q2cli/q2cli/handlers.py", line 185, in get_value
    return self._locate_value(arguments, fallback)
  File "/Users/mcdonadt/ResearchWork/software/q2cli/q2cli/handlers.py", line 59, in _locate_value
    v = arguments[click_name]
KeyError: 'o_gene-families'
```

**Comment by ebolyen** [comment]
I think we expect output names to be Python identifiers (they are just analogues for the parameters, Python just doesn't have named outputs).

**Comment by jairideout** [comment]
Closing in favor of https://github.com/qiime2/qiime2/issues/236
